on:
  workflow_dispatch:


jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    name: test it!
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    steps:
    
    - name: checkout a
      uses: actions/checkout@v3
      with: 
        path: 'a'
        persist-credentials: false
      
    - name: checkout b
      uses: actions/checkout@v3
      with:
        path: 'b'
        repository: '2Akuma2/b'
        token: ${{ secrets.BOT_TOKEN }}
        persist-credentials: true
        fetch-depth: 0
    
    - name: check a&b
      shell: bash
      run: |
        ls a
        ls b
    
    - name: copy a.txt
      run: cp a/a.txt b
    
    - name: check a&b
      shell: bash
      run: |
        ls a
        ls b
    
    - name: check for new files
      id: newFiles
      shell: bash
      working-directory: b
      run: |
        git add -A
        git status --porcelain | wc -l
        if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
          echo "::set-output name=hasNewFiles::true"
        else
          echo "::set-output name=hasNewFiles::false"
        fi
    
    - name: push b
      if: ${{ steps.newFiles.outputs.hasNewFiles == 'true' }}
      shell: bash
      working-directory: b
      run: |
        git config --global user.name "2Akuma2"
        git config --global user.email "${{ secrets.BOT_EMAIL }}"
        git commit -m "Update executed"
        git push
